name: SpyGameiOS

options:
    bundleIdPrefix: com.SpyGameiOS
    minimumXcodeGenVersion: 2.35.0
    xcodeVersion: 14.1
    deploymentTarget:
        iOS: 16.0
    groupSortPosition: top

configs:
    Debug: debug
    Beta: release
    AppStore: release
    
targets:
    SpyGame:
        type: application
        platform: iOS
        deploymentTarget: 16.0
        settings:
            base:
                INFOPLIST_FILE: SpyGameiOS/Info.plist
                MARKETING_VERSION: 1.0
                CURRENT_PROJECT_VERSION: 1.0.0
        sources:
            - path: SpyGameiOS
