name: SpyGameiOS

options:
  bundleIdPrefix: com.SpyGameiOS
  deploymentTarget: '14.0'
  
configs:
  Debug.Dev: debug
  Debug.Prod: debug
  Release: release

targets:
  SpyGame:
    type: application
    platform: iOS
    deploymentTarget: 14.0
    settings:
      base:
        MARKETING_VERSION: 1.0
    sources:
       - path: ../SpyGameiOS
